---
daemon:
  listen: 0.0.0.0
  port: 9876
  base_url: "/api/v0"

faster_whisper:
  model_cache_dir: /tmp/whisper-cache
  model: large-v3
  device: cuda
  device_id: 0
  compute_type: int8
  beam_size: 16
  translate: no
  language: ru
